apiVersion: apps/v1
kind: Deployment
metadata:
  name: poi
  namespace: api
  labels:
    app: poi
spec:
  replicas: 2
  selector:
    matchLabels:
      app: poi
  template:
    metadata:
      labels:
        app: poi
    spec:
      containers:
        - name: poi
          image: registryjzg0978.azurecr.io/poi:v1
          ports:
            - containerPort: 80
          volumeMounts:
          - name: secrets-store01-inline
            mountPath: "/mnt/secrets-store"
            readOnly: true            
          env:
            - name: SQL_USER
              valueFrom:
                secretKeyRef:
                  name: azure-kvname-user-msi
                  key: username
            - name: SQL_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: azure-kvname-user-msi
                  key: password
            - name: SQL_SERVER
              valueFrom:
                secretKeyRef:
                  name: azure-kvname-user-msi
                  key: server            
            - name: SQL_DBNAME
              valueFrom:
                secretKeyRef:
                  name: azure-kvname-user-msi
                  key: dbname
      volumes:
        - name: secrets-store01-inline
          csi:
            driver: secrets-store.csi.k8s.io
            readOnly: true
            volumeAttributes:
              secretProviderClass: "azure-kvname-user-msi"
---
apiVersion: v1
kind: Service
metadata:
  name: poi
  namespace: api
spec:
  ports:
    - port: 80
      protocol: TCP
  selector:
    app: poi
