apiVersion: apps/v1
kind: Deployment
metadata:
  name: userprofile
  namespace: api
  labels:
    app: userprofile
spec:
  replicas: 2
  selector:
    matchLabels:
      app: userprofile
  template:
    metadata:
      labels:
        app: userprofile
    spec:
      containers:
        - name: userprofile
          image: registryjzg0978.azurecr.io/userprofile:v1
          ports:
            - containerPort: 80
          env:
            - name: SQL_USER
              valueFrom:
                secretKeyRef:
                  name: secrets
                  key: username
            - name: SQL_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: secrets
                  key: password
            - name: SQL_SERVER
              valueFrom:
                secretKeyRef:
                  name: secrets
                  key: server            
            - name: SQL_DBNAME
              valueFrom:
                secretKeyRef:
                  name: secrets
                  key: dbname
---
apiVersion: v1
kind: Service
metadata:
  name: userprofile
spec:
  ports:
    - port: 80
      protocol: TCP
  selector:
    app: userprofile
