# This is a SecretProviderClass example using user-assigned identity to access your key vault
apiVersion: secrets-store.csi.x-k8s.io/v1
kind: SecretProviderClass
metadata:
  name: azure-kvname-user-msi
spec:
  provider: azure
  parameters:
    usePodIdentity: "false"
    useVMManagedIdentity: "true"          # Set to true for using managed identity
    userAssignedIdentityID: dfc3df52-07c2-410a-a572-c7181e4215e8   # Set the clientID of the user-assigned managed identity to use
    keyvaultName: tripViewKeyVault        # Set to the name of your key vault
    cloudName: ""                         # [OPTIONAL for Azure] if not provided, the Azure environment defaults to AzurePublicCloud
    objects:  |
      array:
        - |
          objectName: dbname
          objectType: secret 
          objectName: password
          objectType: secret 
          objectName: server
          objectType: secret 
          objectName: username
          objectType: secret                               
    tenantId: 4fe5cf97-5135-4639-bf6d-9d7c44445eac                 # The tenant ID of the key vault