kind: Role
apiVersion: rbac.authorization.k8s.io/v1
metadata:
  name: web-user-read-access
  namespace: web
rules:
- apiGroups: ["", "extensions", "apps"]
  resources: ["*"]
  verbs:
  - get
  - list
  - watch
