---
kind: RoleBinding
apiVersion: rbac.authorization.k8s.io/v1
metadata:
  name: api-user-full-access-to-api
  namespace: api
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: Role
  name: api-user-full-access
subjects:
- kind: Group
  namespace: api
  name: 72d11dce-9c59-402a-b082-ce0fb9ca5e81
---
kind: RoleBinding
apiVersion: rbac.authorization.k8s.io/v1
metadata:
  name: api-user-read-access-to-web
  namespace: web
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: Role
  name: web-user-read-access
subjects:
- kind: Group
  namespace: api
  name: 72d11dce-9c59-402a-b082-ce0fb9ca5e81  
---
kind: RoleBinding
apiVersion: rbac.authorization.k8s.io/v1
metadata:
  name: web-user-read-access-to-api
  namespace: api
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: Role
  name: api-user-read-access
subjects:
- kind: Group
  namespace: web
  name: 511d4e40-9ddd-4278-a629-f8c2f1c42806
---
kind: RoleBinding
apiVersion: rbac.authorization.k8s.io/v1
metadata:
  name: web-user-full-access-to-web
  namespace: web
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: Role
  name: web-user-full-access
subjects:
- kind: Group
  namespace: web
  name: 511d4e40-9ddd-4278-a629-f8c2f1c42806

